### ISSUE TITLE
requirejs dependency definitions

### ISSUE THREAD

**Issue by oliverfoster** [KingsOnline/adapt-google-analytics#4]
https://github.com/KingsOnline/adapt-google-analytics/blob/master/js/adapt-google-analytics.js#L1-L3 these lines would be better written as:

```
define([
    'core/js/adapt'
], function(Adapt) {
```

the coreJS coreViews etc stuff is now redundant. use folder references as above ^

**Comment by simondate** [comment]
Fixed in 5dcaa2e
